language: python
python:
  - "2.7"
before_script:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - export PATH=/home/travis/miniconda/bin:$PATH
  - ./miniconda.sh install --yes scipy=0.17 numpy=1.11
install: true
script: ./dev-scripts/run-tests.sh
