sudo: false
language: python
notifications:
  email:
    recipients:
      - me@arranschlosberg.com
    on_success: change
    on_failure: always
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
cache: apt
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy pandas requests
script:
  - ./dev-scripts/run-tests.sh
